apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullsecret-injector-webhook-deployment
  namespace : {{ .Release.Namespace }}
  labels:
    app: imagepullsecret-injector
    {{- include "imagepullsecret-injector.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepullsecret-injector
  template:
    metadata:
      labels:
        app: imagepullsecret-injector
    spec:
      serviceAccountName: imagepullsecret-injector
      containers:
        - name: imagepullsecret-injector
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
          - 2>&1
          env:
            - name: CONFIG_PORT
              value: "8443"
            - name: CONFIG_CERT_PATH
              value: "/etc/webhook/certs/tls.crt"
            - name: CONFIG_KEY_PATH
              value: "/etc/webhook/certs/tls.key"
            - name: CONFIG_EXCLUDE_NAMESPACES
              value: {{ join "," .Values.imagepullsecretInjector.excludeNamespaces | quote }}
            - name: CONFIG_SERVICE_ACCOUNTS
              value: {{ join "," .Values.imagepullsecretInjector.saNames | quote }}
            - name: CONFIG_TARGET_IMAGE_PULL_SECRET_NAME
              value: {{ .Values.imagepullsecretInjector.targetSecretName | quote }}
            - name: CONFIG_SOURCE_IMAGE_PULL_SECRET_NAME
              value: {{ .Values.imagepullsecretInjector.dockerconfigjsonRef.secretName | quote }}
            - name: CONFIG_SOURCE_IMAGE_PULL_SECRET_NAMESPACE
              value: {{ .Values.imagepullsecretInjector.dockerconfigjsonRef.secretNamespace | default .Release.Namespace | quote }}
            - name: CONFIG_IGNORE_SECRET_CREATION_ERROR
              value: {{ .Values.imagepullsecretInjector.ignoreSecretCreationError | quote }}
            - name: CONFIG_ALL_SERVICE_ACCOUNTS
              value: {{ .Values.imagepullsecretInjector.allSaNames | quote }}
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ include "imagepullsecret-injector.certificateSecretName" . }}