apiVersion: v1
kind: Service
metadata:
  name: {{ include "imagepullsecret-injector.serviceName" . }}
  namespace : {{ .Release.Namespace }}
  labels:
    app: imagepullsecret-injector
    {{- include "imagepullsecret-injector.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: imagepullsecret-injector
