apiVersion: v1
kind: ConfigMap
metadata:
  name: imagepullsecret-injector-cert-gen-entrypoint
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagepullsecret-injector.labels" . | nindent 4 }}
data:
  entrypoint.sh: | {{ .Files.Get "scripts/create-signed-cert.sh" | nindent 4 }}
