image:
  registry: ghcr.io/ysoftdevs/imagepullsecret-injector
  repository: imagepullsecret-injector
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagepullsecretInjector:
  dockerconfigjsonRef:
    secretName: acr-dockerconfigjson-source
    secretNamespace: ""

  targetSecretName: acr-dockerconfigjson
  ignoreSecretCreationError: false
  allSaNames: false
  saNames:
    - default
  excludeNamespaces:
    - kube-system
    - traefik
    - datadog

certificateGenerator:
  cronJobSchedule: '0 0 * * 0' # At 00:00 on Sunday

clusterIssuer: "webhook-issuer"