image:
  registry: ghcr.io/ysoftdevs/imagepullsecret-injector
  repository: imagepullsecret-injector
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

certificateGeneratorImage:
  registry: ghcr.io/ysoftdevs/imagepullsecret-injector
  repository: webhook-cert-generator
  tag: ""

imagepullsecretInjector:
  dockerconfigjsonRef:
    secretName: acr-dockerconfigjson-source
    secretNamespace: ""

  targetSecretName: acr-dockerconfigjson
  ignoreSecretCreationError: false
  allSaNames: false
  saNames:
    - default
  excludeNamespaces:
    - kube-system
    - traefik
    - datadog
