name: Release docker images

on:
  push:
    branches:
      - main
      - devel

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Build and push docker images (make image)
        run: make image
        env:
          DOCKER_USER: '${{ secrets.DOCKER_USER }}'
          DOCKER_TOKEN: '${{ secrets.DOCKER_TOKEN }}'

      - name: Logout from dockerhub (make docker-logout)
        run: make docker-logout